Solutions for 08: product form
js-tasks-ru/js-20201211_gelyako pull request #10
Opened 2021-01-14 05:11 UTC by konvi

2021-01-14 05:18 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ProductForm v1 компонент с отправкой данных на сервер, без "Drag'n'Drop"
+ should be rendered correctly
+ should render categories data correctly
+ should render product data correctly
+ should dispatch "product-updated" event after product creating
+ should have ability to be removed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-01-14 05:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-01-15 15:28 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +      const {title, description, price, discount, quantity, status, images} = this.product;
Было бы неплохо данный кусок кода оптимизировать - заменив на цикл в котором мы будем присваивать данные в элементы формы. Более того с точки зрения логики данную операцию следует вынести в отдельный метод

2021-01-15 15:29 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +    await this.getCategories();
помните мы говорили на занятии о том что неплохо было бы запрашивать независимые данные параллельно. Подумайте можно ли это сделать в данной реализации

2021-01-15 15:31 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +class ImageUploader {
да, можно переиспользовать логику ImageUploader класса, но сам класс здесь не нужен. Следует переместить его содержимое внутрь соответствующего метода ProductForm

2021-01-15 15:31 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-01-17 04:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-01-17 04:18 UTC, konvi commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +    await this.getCategories();
Изменено на `await Promise.all([this.getCategories(), this.loadData()]);`

2021-01-17 04:20 UTC, konvi commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +      const {title, description, price, discount, quantity, status, images} = this.product;
Изменено на copy/paste c solution'а, сама бы не написала.
```javascript
setFormData () {
    const { productForm } = this.subElements;
    const excludedFields = ['images'];
    const fields = Object.keys(this.defaultFormData).filter(item => !excludedFields.includes(item));

    fields.forEach(item => {
      const element = productForm.querySelector(`#${item}`);
      element.value = this.formData[item] || this.defaultFormData[item];
    });
```

2021-01-17 04:28 UTC, konvi commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +class ImageUploader {
Перенесла в метод.

2021-01-17 15:29 UTC, dosandk approved these changes
good 👍

2021-01-17 15:29 UTC, merged